/*
 * Panel de buscar.
 * Se elegirá a partir del Combo de marcas la marca que se quiere buscar. Al
 * pulsar cambiará al panel de la lista de modelos para mostrar los modelos
 * asociados a la marca seleccionada
 */
package com.cice.ui;

import com.cice.controller.GestorMarcas;
import javax.swing.JOptionPane;

/**
 *
 * @author AVECH3H
 */
public class JPBuscar extends javax.swing.JPanel {

    //Constantes
    private static final String ERR_OPCI = "Debe elegir una marca de búsqueda";
    private static final String PANEL_LISTA = "PanelListaModelos";
    //Variables de la clase
    private JFGestorMotor jfg;
    private MarcasComboModel mcm = null; 
    private GestorMarcas gm = new GestorMarcas();
    /**
     * 
     * @param jfg: Objeto JFRAME de la aplicación
     */
    public JPBuscar(JFGestorMotor jfg) {
        initComponents();
        this.jfg = jfg;
        inicializarCombo();
    }

    /**
     * Inicializa el combo de marcas
     */
    public void inicializarCombo() {
        try {
            mcm = new MarcasComboModel(gm.getMarcas());
            jcbListaMarcas.setModel(mcm);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbListaMarcas = new javax.swing.JComboBox<>();
        jbBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jcbListaMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbBuscar.setText("BUSCAR");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Marcas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jcbListaMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbBuscar)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar)
                    .addComponent(jcbListaMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(291, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt: Evento del botón buscar. Al seleccionar un elemento de la 
     * lista se llamará al siguiente panel para mostrar los modelos de la
     * marca seleccionada
     */
    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        int selectedIndex = jcbListaMarcas.getSelectedIndex();
        int idMarcaSelected = ((MarcasComboModel)jcbListaMarcas.getModel()).getIdMarca(selectedIndex);
        
        if (idMarcaSelected != 0){
            jfg.instanciaLista(idMarcaSelected, jfg);
            jfg.cambiarPanel(PANEL_LISTA);
        } else{
            showDialog(ERR_OPCI);
        }
    }//GEN-LAST:event_jbBuscarActionPerformed
    
    private void showDialog(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JComboBox<String> jcbListaMarcas;
    // End of variables declaration//GEN-END:variables
}
