/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cice.ui;

import com.cice.controller.GestorModelos;
import com.cice.model.Modelo;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author AVECH3H
 */
public class JPListaModelos extends javax.swing.JPanel {

    /**
     * Creates new form JPListaModelos
     */
    public JPListaModelos(int idMarca) {
        initComponents();
        cargarDatos(idMarca);
    }
    
    public void cargarDatos(int idMarca) {
        GestorModelos gm = new GestorModelos();
        List<Modelo> modelos = null;
        ModelosTableModel mtm = null;

        try {
            modelos = gm.getModelosMarca(idMarca);
            mtm = new ModelosTableModel(modelos);
            jTableModelos.setModel(mtm);
        } catch (Exception ex) {
            showDialog(ex.getMessage());
        }
    }
    
    private void showDialog(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableModelos = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-trash-25.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jTableModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "MODELO", "CONSUMO", "EMISIONES", "C_ENERGETICA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Short.class, java.lang.Short.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableModelos);
        if (jTableModelos.getColumnModel().getColumnCount() > 0) {
            jTableModelos.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTableModelos.getColumnModel().getColumn(3).setResizable(false);
            jTableModelos.getColumnModel().getColumn(4).setResizable(false);
            jTableModelos.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (confirmarBorrado()) {
            borrarUsuario();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void borrarUsuario() {
        int filaSeleccionada = jTableModelos.getSelectedRow();

        if (filaSeleccionada == -1) {
            showDialog("Debe tener una fila seleccionada");
        } else {
            try {
                GestorModelos gm = new GestorModelos();
                int idModelo = (int) jTableModelos.getModel().getValueAt(filaSeleccionada, 4);
                gm.deleteModelo(idModelo);
            } catch (Exception ex) {
                showDialog(ex.getMessage());
            }
        }
    }

    private boolean confirmarBorrado() {
        int n = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro que quiere eliminar el modelo?",
                "Borrado de Modelo",
                JOptionPane.YES_NO_OPTION);

        return (n == JOptionPane.OK_OPTION);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableModelos;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
